GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJmYXRodWxsYWggbXVuYWRpIiwiZW1haWwiOiJtdW5hZGlAZ21haWwuY29tIiwiaWF0IjoxNjY5MjU5MjI3LCJleHAiOjE2NjkyNTkyNDJ9.M2J3qB_pvATE2jD_haoRf4dfjOG0YYhyUqp9xg1J-jI
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"fathullah munadi",
    "email":"munadi@gmail.com",
    "password":"123456",
    "confPassword":"123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "munadi@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token


###
DELETE  http://localhost:5000/logout